# Generated by Django 4.1.5 on 2023-02-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='logo/%Y%m%d'),
        ),
    ]
