# Generated by Django 4.1.6 on 2023-02-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('mixed', '혼성')], default='', max_length=10),
        ),
    ]
