# Generated by Django 4.1.6 on 2023-02-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchinfo',
            old_name='is_alarmed',
            new_name='host_rated',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='participant_rated',
            field=models.BooleanField(default=False),
        ),
    ]
