# Generated by Django 4.1.6 on 2023-02-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='writer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
