# Generated by Django 4.1.6 on 2023-02-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0002_team_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='gender',
        ),
    ]
