# Generated by Django 4.1.5 on 2023-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0002_alter_matchinfo_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='manner',
            field=models.FloatField(default=0, null=True),
        ),
    ]
