# Generated by Django 4.1.5 on 2023-02-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0002_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
