# Generated by Django 4.1.5 on 2023-02-10 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0004_alter_matchinfo_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
