# Generated by Django 4.1.5 on 2023-02-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0003_alter_matchinfo_host_id'),
        ('matchingMatch', '0004_alter_matchinfo_host_id'),
    ]

    operations = [
    ]
