# Generated by Django 4.1.5 on 2023-02-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingMatch', '0004_alter_matchinfo_participant_id'),
        ('matchingMatch', '0006_alter_alarm_match_id_alter_team_photo_and_more'),
    ]

    operations = [
    ]
