from django.urls import path
from . import views
app_name = "matchingMatch"

urlpatterns = [
    path("match_register", views.match_register, name="match_register"),
    path("", views.main, name="main"),
    path('login/', views.login_page, name="login"),
    path('register/', views.register_page, name="register"),
    path('register/success', views.register_success, name = "register_success"),
    path('logout/', views.logout_user, name="logout"),
    path('account/', views.account_page, name="account"),
    path('my_register_matches/<int:pk>', views.my_register_matches, name="my_register_matches"),
    path('my_apply_matches/<int:pk>', views.my_apply_matches, name="my_apply_matches"),
    path('match_detail/<int:pk>', views.match_detail, name="match_detail"),
    path('applying_team_list/<int:pk>',
         views.applying_team_list, name="applying_team_list"),
    path('match_detail/<int:pk>', views.match_detail, name="match_detail"),
    path('match_request/', views.match_request, name = "match_request"),
    path('match_cancel/', views.match_cancel, name = "match_cancel"),
    path('edit-account/', views.edit_account, name="edit-account"),
    path('change-password/', views.change_password, name="change-password"),
    path('change_enroll/', views.change_enroll, name='change_enroll'),
    path('team_list/', views.team_list, name ='team_list'),
    path('delete-account/<int:pk>', views.delete_account.as_view(), name="delete-account"),
    path('match_update/<int:pk>', views.match_update, name = "match_update"),
    path('match_delete/<int:pk>', views.match_delete, name = "match_delete"),
    path('team_detail/<int:pk>',  views.team_detail, name = "team_detail"),
    path('rate/<int:pk>', views.rate, name="rate"),
    path('match/ended/', views.check_endedmatch, name="check_endedmatch"),
    path('notice_list/', views.notice_list, name="notice_list"),
    path('notice_create/', views.notice_create, name="notice_create"),
    path('notice_detail/<int:pk>', views.notice_detail, name="notice_detail"),
    path('notice_detail/<int:pk>/update', views.notice_update, name="notice_update"),
    path('notice_detail/<int:pk>/delete', views.notice_delete, name="notice_delete"),
    path('report_list/', views.report_list, name="report_list"),
    path('report_create/', views.report_create, name="report_create"),
    path('report_detail/<int:pk>', views.report_detail, name="report_detail"),
    path('report_detail/<int:pk>/update', views.report_update, name="report_update"),
    path('report_detail/<int:pk>/delete', views.report_delete, name="report_delete"),
    
]
